name: gatello
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  scroll_date_picker: ^3.4.0
  flutter_holo_date_picker: ^1.0.3
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  country_icons: ^2.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.2
  hexcolor: ^2.0.7
  otp_text_field: ^1.1.3
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.1+1
  grouped_list: ^5.1.2
  flutter_chat_bubble: ^2.0.0
  http: ^0.13.4
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  webview_flutter: ^2.0.9
  shared_preferences: ^2.0.6
  email_validator: ^2.0.1
  flutter_pw_validator: ^1.4.2
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  flutter_launcher_icons: ^0.9.3
  double_back_to_close_app: ^2.1.0
  fluttertoast: ^8.0.9
#  cloud_firestore: ^3.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: 
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/appbar_action/Rectangle 7.png
    - assets/profile_page/profile_pic_logo.png
    - assets/invite_friends/invite_friends_logo.png
    - assets/birthday_image/birthday_logo.png 
    - assets/splash_1/glogo.png
    - assets/splash2_image/splah2 _image.png
    - assets/splash3_image/splash3_image.png
    - assets/icons_assets/add_friends_button.png
    - assets/Gatello_logo/Gatello_temp_logo.png
    - assets/tabbar_icons/chats_image/chats_empty.png
    - assets/icons_assets/chat_icon_floating.svg
    - assets/tabbar_icons/getit_icon.png
    - assets/tabbar_icons/pings_icon.png
    - assets/tabbar_icons/status_icon.png
    - assets/tabbar_icons/call_icon.png
    - assets/icons_assets/new_group.png
    - assets/splash2_image/right_arrow.png
    - assets/splash3_image/left_arrow.png
    - assets/per_chat_icons/chat_background_image.png
    - assets/per_chat_icons/mic_icon.svg
    - assets/splash_1/glogo.png
    - assets/per_chat_icons/attach_file_icon.png
    - assets/camera_icon/camera.png
    - assets/per_chat_icons/smiley_icon.png
    - assets/dp_image/dp_icon_male.png
    - assets/forgot_scren_image/forgot_image.png
    - assets/email_image/email_icon.png
    - assets/icons_assets/down_arrow.png
    - assets/per_chat_icons/video.png
    - assets/per_chat_icons/menu_icon.png
    - assets/per_chat_icons/back_icon.png
    - assets/per_chat_icons/call_icon.svg
    - assets/per_chat_icons/video icon.svg
    - assets/per_chat_icons/camera.png
    - assets/per_chat_icons/dp_image.svg
    - assets/linked device image/Gatello_box.png
    - assets/group_info/search.png
    - assets/group_info/add contants.png
    - assets/group_info/calls.png
    - assets/group_info/edit_icon.png
    - assets/group_info/video icon.png
    - assets/group_info/add participants.png
    - assets/group_info/invite link.png
    - assets/select_contact/right arrow icon.png
    - assets/icons_assets/visibility_icon.png
    - assets/tabbar_icons/chats_image/attachment_icon_container/document_icon_container.png
    - assets/tabbar_icons/chats_image/attachment_icon_container/camera_icon_container.png
    - assets/tabbar_icons/chats_image/attachment_icon_container/gallery_icon_container.png
    - assets/tabbar_icons/chats_image/attachment_icon_container/audio_icon_container.png
    - assets/tabbar_icons/chats_image/attachment_icon_container/location_icon_container.png
    - assets/tabbar_icons/chats_image/attachment_icon_container/contact_icon_container.png
    - assets/tabbar_icons/chats_image/video_call_icon.svg
    - assets/icons_assets/green_tick.svg
    - assets/select_contact/invite friends.svg
    - assets/select_contact/new contact.svg
    - assets/select_contact/new group.svg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #      - asset: assets/fonts/Helvetica-Font/Helvetica-Bold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # fonts:
  # - family: Schyler
  #    fonts:
  #     - asset: fonts/Schyler-Regular.ttf
  #     - asset: fonts/Schyler-Italic.ttf
  #      style: italic
  # - family: Trajan Pro
  #  fonts:
  #    - asset: fonts/TrajanPro.ttf
  #     - asset: fonts/TrajanPro_Bold.ttf
  #      weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
