name: gatello
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  scroll_date_picker: ^3.4.0
  flutter_holo_date_picker: ^1.0.3
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  english_words: ^4.0.0
  country_icons: ^2.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.2
  hexcolor: ^2.0.7
  otp_text_field: ^1.1.3
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.1+1
  grouped_list: ^5.1.2
  flutter_chat_bubble: ^2.0.0
  http: ^0.13.4
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  webview_flutter: ^2.0.9
  shared_preferences: ^2.0.6
  email_validator: ^2.0.1
  flutter_pw_validator: ^1.4.2
  firebase_auth: ^3.4.2
  firebase_core: ^1.20.0
  double_back_to_close_app: ^2.1.0
  cloud_firestore: ^3.4.0
  fluttertoast: ^8.0.9
  wp_search_bar: ^0.0.5
  timezone: ^0.8.0
  firebase_storage: ^10.3.10
  firebase_messaging: ^12.0.1
  android_path_provider: ^0.3.0
  tuple: ^2.0.0
  permission_handler: ^10.0.0
  device_info_plus: ^4.0.1
  path_provider: ^2.0.11
  lottie: ^1.4.1
  emoji_picker_flutter: ^1.3.1
  cached_network_image: ^3.2.1
  responsive_builder: ^0.4.2
  preload_page_view: ^0.1.6
  file_picker: ^5.0.1
  flutter_switch: ^0.3.2
  flick_video_player: ^0.5.0
  video_player: ^2.4.5
  visibility_detector: ^0.3.3
  flutter_local_notifications: ^9.7.0
  flutter_callkit_incoming: ^1.0.2+1
  dropdown_button2: ^1.7.1
  overlay_support: ^2.0.1
  logger: ^1.1.0
  carousel_slider: ^4.1.1
  fluttericon: ^2.0.0
  substring_highlight: ^1.0.33
  audioplayers: ^0.20.1
  url_launcher: ^6.0.17
  contacts_service: ^0.6.3
  swipe_to: ^0.1.0-nullsafety.1
  record: ^3.0.4
  nanoid: ^1.0.0
  fast_contacts: ^1.1.1
  mime: ^1.0.1
  giphy_picker: ^2.0.0
  location: ^4.3.0
  adaptive_theme: ^3.1.1
  firebase_dynamic_links: ^4.3.4
  flutter_speed_dial: ^6.0.0
  story_view: ^0.13.2
  clipboard: ^0.1.3
  fluttercontactpicker: ^4.7.0
  flutter_downloader: ^1.8.4
  flutter_image_compress: ^1.1.3
  get: ^4.6.5
  flutter_file_downloader: ^1.1.0+1
  sms_autofill: ^2.2.0
  provider: ^6.0.4
  image_cropper: ^3.0.1
  alt_sms_autofill: ^1.0.0
  pin_code_fields: ^7.4.0
  flutter_native_splash: ^2.2.15
  flutter_colorpicker: ^1.0.3
  page_transition: ^2.0.9
  get_storage: ^2.0.3
  connectivity_plus: ^3.0.2
  firebase_database: ^9.1.7
  story: ^0.8.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/gat_logo/logo.png'
  android: true
  ios: true
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
flutter_native_splash:
  image:assets/gatellologo1.gif
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/appbar_action/Rectangle 7.png
    - assets/profile_page/profile_pic_logo.png
    - assets/splash_1/glogo.png
    - assets/splash2_image/splah2 _image.png
    - assets/splash3_image/splash3_image.png
    - assets/icons_assets/add_friends_button.png
    - assets/Gatello_logo/Gatello_temp_logo.png
    # - assets/tabbar_icons/chats_image/chats_empty.png
    - assets/icons_assets/chat_icon_floating.svg
    - assets/icons_assets/new_group.png
    - assets/splash2_image/right_arrow.png
    - assets/splash3_image/left_arrow.png
    - assets/per_chat_icons/chat_background_image.png
    - assets/per_chat_icons/mic_icon.svg
    - assets/splash_1/glogo.png
    - assets/per_chat_icons/attach_file_icon.png
    - assets/camera_icon/camera.png
    - assets/per_chat_icons/smiley_icon.png
    - assets/dp_image/dp_icon_male.png
    - assets/forgot_scren_image/forgot_image.png
    - assets/email_image/email_icon.png
    - assets/icons_assets/down_arrow.png
    - assets/per_chat_icons/video.png
    - assets/per_chat_icons/menu_icon.png
    - assets/per_chat_icons/back_icon.png
    - assets/per_chat_icons/call_icon.svg
    - assets/per_chat_icons/video icon.svg
    - assets/per_chat_icons/camera.png
    - assets/per_chat_icons/dp_image.svg
    - assets/linked device image/Gatello_box.png
    - assets/group_info/search.png
    - assets/group_info/add contants.png
    - assets/group_info/calls.png
    - assets/group_info/edit_icon.png
    - assets/group_info/video icon.png
    - assets/group_info/add participants.png
    - assets/group_info/invite link.png
    - assets/select_contact/right arrow icon.png
    - assets/icons_assets/visibility_icon.png
    - assets/tabbar_icons/tab_view_main/chats_image/emptyChat.png
    - assets/tabbar_icons/tab_view_main/chats_image/attachment_icon_container/audio_image.svg
    - assets/tabbar_icons/tab_view_main/chats_image/attachment_icon_container/camera_image.svg
    - assets/tabbar_icons/tab_view_main/chats_image/attachment_icon_container/contact_img.svg
    - assets/tabbar_icons/tab_view_main/chats_image/attachment_icon_container/doc_image.svg
    - assets/tabbar_icons/tab_view_main/chats_image/attachment_icon_container/gallery_image.svg
    - assets/tabbar_icons/tab_view_main/chats_image/attachment_icon_container/location_img.svg
    - assets/tabbar_icons/Tabbar_search.svg
    - assets/icons_assets/green_tick.svg
    - assets/select_contact/invite friends.svg
    - assets/select_contact/new contact.svg
    - assets/select_contact/new group.svg
    - assets/tabbar_icons/tab_view_main/invite frds tab.svg
    - assets/tabbar_icons/tab_view_main/linked devices tab.svg
    - assets/tabbar_icons/tab_view_main/new group tab.svg
    - assets/tabbar_icons/tab_view_main/settings_icon.svg
    - assets/icons_assets/wrong.svg
    - assets/per_chat_icons/sendIcon.svg
    - assets/tabbar_icons/tab_view_main/chats_image/video_search.svg
    - assets/tabbar_icons/tab_view_main/chats_image/doc_search.svg
    - assets/tabbar_icons/tab_view_main/chats_image/per_chat_ontap_icons/backward.svg
    - assets/tabbar_icons/tab_view_main/chats_image/per_chat_ontap_icons/delete.svg
    - assets/tabbar_icons/tab_view_main/chats_image/per_chat_ontap_icons/forward.svg
    - assets/tabbar_icons/tab_view_main/archieved_icon.svg
    - assets/pops_asset/pops_gallery.svg
    - assets/welcomeback.png
    - assets/pops_asset/pops_likebutton.svg
    - assets/pops_asset/pops_commentbutton.svg
    - assets/pops_asset/pops_share.svg
    - assets/pops_asset/pops_savebutton.svg
    - assets/pops_asset/pops_sharefinal.svg
    - assets/pops_asset/search_image.svg
    - assets/pops_asset/Search-popsfinal.svg
    - assets/pops_asset/Final_tick.svg
    - assets/pops_asset/new_post_gallery.svg
    - assets/pops_asset/Tag_people.svg
    - assets/pops_asset/Location_image.svg
    - assets/pops_asset/liked.svg
    - assets/pops_asset/searchicon.svg
    - assets/tabbar_icons/tab_view_main/back_icon.svg
    - assets/pops_asset/floating_comment.svg
    - assets/pops_asset/interactions.svg
    - assets/pops_asset/tagpeople.svg
    - assets/call_assets/noconversation.svg
    - assets/call_assets/callsymbol.svg
    - assets/call_assets/calldecline - Copy.svg
    - assets/call_assets/chat_call.svg
    - assets/call_assets/arrow_upward.svg
    - assets/call_assets/arrow2.svg
    - assets/call_assets/arrow3.svg
    - assets/profile_assets/back_button.svg
    - assets/profile_assets/call_outline.svg
    - assets/pops_asset/LikebuttonGe.svg
    - assets/pops_asset/commentge.svg
    - assets/pops_asset/sharegee.svg
    - assets/pops_asset/galleryge.svg
    - assets/pops_asset/photosge.svg
    - assets/pops_asset/tagge.svg
    - assets/profile_assets/Edit_tool.svg
    - assets/profile_assets/edittoolblack.svg
    - assets/profile_assets/privateaccount.svg
    - assets/profile_assets/proffesion.svg
    - assets/profile_assets/videoplay.svg
    - assets/profile_assets/commentnotifi.svg
    - assets/profile_assets/bornon.svg
    - assets/profile_assets/profilecall.svg
    - assets/profile_assets/profilelink.svg
    - assets/profile_assets/searchicon.svg
    - assets/profile_assets/profilelanguage.svg
    - assets/tabbar_icons/pops_getit.svg
    - assets/tabbar_icons/Pops_icon.svg
    - assets/tabbar_icons/pings_icon.svg
    - assets/tabbar_icons/status_icon.svg
    - assets/tabbar_icons/pops_call.svg
    - assets/pops_asset/pings_icon.svg
    - assets/pops_asset/interaction_icon.svg
    - assets/pops_asset/gatello_loading.gif
    - assets/pops_asset/gatello_loading2.gif
    - assets/profile_assets/no_profile.svg
    - assets/storage_assets/all_files.svg
    - assets/storage_assets/back-icon.svg
    - assets/storage_assets/filemanager_icon.svg
    - assets/storage_assets/elipse.svg
    - assets/storage_assets/forward_icon.svg
    - assets/storage_assets/photos_icon.svg
    - assets/storage_assets/videos_icon.svg
    - assets/storage_assets/create_folder.svg
    - assets/storage_assets/play_icon.svg
    - assets/storage_assets/audio_icon.svg
    - assets/storage_assets/documents.svg
    - assets/storage_assets/all_files.svg
    - assets/storage_assets/back-icon.svg
    - assets/storage_assets/filemanager_icon.svg
    - assets/storage_assets/elipse.svg
    - assets/storage_assets/forward_icon.svg
    - assets/storage_assets/photos_icon.svg
    - assets/storage_assets/videos_icon.svg
    - assets/storage_assets/create_folder.svg
    - assets/storage_assets/play_icon.svg
    - assets/storage_assets/audio_icon.svg
    - assets/storage_assets/documents.svg
    - assets/status_assets/camera_icon.svg
    - assets/status_assets/back_icon.svg
    - assets/status_assets/delete_icon.svg
    - assets/status_assets/statusview_icon.svg
    - assets/status_assets/statusdetails.svg
    - assets/status_assets/status_text.svg
    - assets/status_assets/chat_attachment.svg
    - assets/status_assets/chat_camera.svg
    - assets/status_assets/voicemsg_icon.svg
    - assets/birthday_image/birthday_icon.svg
    - assets/pops_asset/No_Request_Icon.svg
    - assets/chatLightBg.jpg
    - assets/pops_asset/back_button.svg
    - assets/noProfile.jpg
    - assets/invite_friends/invitefriends.svg
    - assets/invite_friends/profilepicture.svg
    - assets/invite_friends/add_icon.svg
    - assets/icons_assets/invite_link.svg
    - assets/group_info/chat_attachments.svg
    - assets/group_info/cameraicon_chat.svg
    - assets/group_info/add_participants.svg
    - assets/group_info/calls icon.svg
    - assets/group_info/video image.svg
    - assets/group_info/calls icon.svg
    - assets/group_profile.svg
    - assets/gatello_asset/briefLogo.png
    - assets/settngs/QR.svg
    - assets/settngs/account_icon.svg
    - assets/select_contact/right_arrow.svg
    - assets/icons_assets/signup_camera.svg
    - assets/icons_assets/signup_gallery.svg
    - assets/error_icon.svg
    - assets/tabbar_icons/tab_view_main/chats_image/per_chat_ontap_icons/viewoncetf.svg
    - assets/tabbar_icons/tab_view_main/chats_image/per_chat_ontap_icons/receiver_vo.svg
    - assets/gatello.gif
    - assets/gatellologo1.gif
    - assets/audio/
    - assets/Animation - 1669350283797-150x150 1.gif
    - assets/profile_assets/default_cover.svg
    - assets/status_assets/seen_icon.svg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #      - asset: assets/fonts/Helvetica-Font/Helvetica-Bold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # fonts:
  # - family: Schyler
  #    fonts:
  #     - asset: fonts/Schyler-Regular.ttf
  #     - asset: fonts/Schyler-Italic.ttf
  #      style: italic
  # - family: Trajan Pro
  #  fonts:
  #    - asset: fonts/TrajanPro.ttf
  #     - asset: fonts/TrajanPro_Bold.ttf
  #      weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages