// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZRRCJ_m0yfwVo-DEeZ17Beyp5M8XlE_w',
    appId: '1:391313841103:web:2c8904191f1515123a10ba',
    messagingSenderId: '391313841103',
    projectId: 'gatello-5d386',
    authDomain: 'gatello-5d386.firebaseapp.com',
    storageBucket: 'gatello-5d386.appspot.com',
    measurementId: 'G-3DSK9G2QEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAomWdGgiatrauXZHk3PIrbF4hCBpWYHnk',
    appId: '1:391313841103:android:8952842cd858b8323a10ba',
    messagingSenderId: '391313841103',
    projectId: 'gatello-5d386',
    storageBucket: 'gatello-5d386.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY3l_CXjVOKsbsBjbsRFo_zBz0dBAAN0g',
    appId: '1:391313841103:ios:c0d4c10a3baead6d3a10ba',
    messagingSenderId: '391313841103',
    projectId: 'gatello-5d386',
    storageBucket: 'gatello-5d386.appspot.com',
    androidClientId:
        '391313841103-5vemnjp6th85chp0j8o39ombfk43j5k1.apps.googleusercontent.com',
    iosClientId:
        '391313841103-24mjjvg8oi7nev6vhun51lbcq66sfb6j.apps.googleusercontent.com',
    iosBundleId: 'com.gatello.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY3l_CXjVOKsbsBjbsRFo_zBz0dBAAN0g',
    appId: '1:391313841103:ios:c0d4c10a3baead6d3a10ba',
    messagingSenderId: '391313841103',
    projectId: 'gatello-5d386',
    storageBucket: 'gatello-5d386.appspot.com',
    androidClientId:
        '391313841103-5vemnjp6th85chp0j8o39ombfk43j5k1.apps.googleusercontent.com',
    iosClientId:
        '391313841103-24mjjvg8oi7nev6vhun51lbcq66sfb6j.apps.googleusercontent.com',
    iosBundleId: 'com.gatello.user',
  );
}
