/// Flutter icons DeejosIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DeejosIcon
///      fonts:
///       - asset: fonts/DeejosIcon.ttf
///
///
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class DeejosIcon {
  DeejosIcon._();

  static const _kFontFam = 'DeejosIcon';
  static const String? _kFontPkg = null;

  static const IconData about_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attachment_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audio_gallery = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_1_fill = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_1_outline = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_2_fill = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_2_outline = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_icon = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData darkmode_icon = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_outline = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_icon = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_folder = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_icon = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_outline = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_fill = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_gallery = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_camera = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_icon = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outline = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_1_fill_red = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_icon = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_1_outline = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_1_fill = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_outline = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_1_outline = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_outline = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_gallery = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emoji_outline = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData end_call = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filled_profile = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_fill = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData in_incoming_call_fill = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_camera_fill = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData out_going_call_fill = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_book = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gif = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData placeholder = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
